Improve formatting

diff --git a/netif.d/bond b/netif.d/bond
--- a/netif.d/bond
+++ b/netif.d/bond
@@ -1,50 +1,46 @@
 #!/bin/sh
 
 netif_create() {
-
 	ip link add name $interface type bond
 }
 
 netif_destroy() {
-
-ip link delete dev ${interface}
-
+	ip link delete dev ${interface}
 }
-netif_pre_up() {
 
-        for ipnm in $ipaddr $ipaddrs; do
-                ip addr add $ipnm dev $interface || die "Couldn't add $ipnm to $interface"
-        done
-        for ipnm6 in $ipaddr6 $ipaddrs6; do
-                ip -6 addr add $ipnm6 dev $interface || die "Couldn't add $ipnm6 to $interface"
-        done
+netif_pre_up() {
+	for ipnm in $ipaddr $ipaddrs; do
+		ip addr add $ipnm dev $interface || die "Couldn't add $ipnm to $interface"
+	done
+	for ipnm6 in $ipaddr6 $ipaddrs6; do
+		ip -6 addr add $ipnm6 dev $interface || die "Couldn't add $ipnm6 to $interface"
+	done
 }
 
 netif_post_up() {
-    require slaves
+	require slaves
 	local slave
-    local bcast
-     if [ -n "$slaves" ]; then
-         for slave in ${slaves//netif./}; do
+	local bcast
+	if [ -n "$slaves" ]; then
+		for slave in ${slaves//netif./}; do
+			ip link set ${slave} master ${interface}
+		done
+	fi
 
-        ip link set ${slave} master ${interface}
-			done
-		fi
-
-		if [ -n "$polic"]; then
-		 echo "${policy}" > /sys/class/net/${interface}/bonding
-		else
-			echo "policy required. Please use one of the following policies:"
-			echo "active-backup, balance-rr, balance-xor, balance-tlb, balance-alb, broadcast, 802.3ad"
-		fi
+	if [ -n "$polic"]; then
+		echo "${policy}" > /sys/class/net/${interface}/bonding
+	else
+		echo "policy required. Please use one of the following policies:"
+		echo "active-backup, balance-rr, balance-xor, balance-tlb, balance-alb, broadcast, 802.3ad"
+	fi
 }
 
 netif_pre_down() {
 	local slave
-    local bcast
-     if [ -n "$slaves" ]; then
-         for slave in ${slaves//netif./}; do
-        ip link set ${slave} nomaster
-			done
-		fi
+	local bcast
+	if [ -n "$slaves" ]; then
+		for slave in ${slaves//netif./}; do
+			ip link set ${slave} nomaster
+		done
+	fi
 }
diff --git a/netif.d/bridge-dhcpcd b/netif.d/bridge-dhcpcd
--- a/netif.d/bridge-dhcpcd
+++ b/netif.d/bridge-dhcpcd
@@ -9,39 +9,39 @@ netif_depend() {
 
 netif_create() {
 	ip link add name $interface type bridge
-        if [ -n "$fd" ]; then
-           echo $fd > /sys/devices/virtual/net/${interface}/bridge/forward_delay
-        else
-           echo  0 > /sys/devices/virtual/net/${interface}/bridge/forward_delay
-        fi
-        for f in /proc/sys/net/bridge/bridge-nf-*; do echo 0 > $f; done
+	if [ -n "$fd" ]; then
+		echo $fd > /sys/devices/virtual/net/${interface}/bridge/forward_delay
+	else
+		echo  0 > /sys/devices/virtual/net/${interface}/bridge/forward_delay
+	fi
+	for f in /proc/sys/net/bridge/bridge-nf-*; do echo 0 > $f; done
 	if [ -n "$mac_addr" ]; then
-	     echo 'mac_addr is deprecated and will be removed. Please use "macaddr"'
-	if [ -n "$macaddr" ]; then
-        echo "Warning, \$macaddr is set. Using \$macaddr value $maccaddr"
-        else
-	    macaddr=$mac_addr
-        fi 
-    fi 
-        if [ -n "$stp" ]; then
-           echo "$stp" > /sys/devices/virtual/net/${interface}/bridge/stp_state         
-        else
-           echo "0" > /sys/devices/virtual/net/${interface}/bridge/stp_state
-        fi 
+		echo 'mac_addr is deprecated and will be removed. Please use "macaddr"'
+		if [ -n "$macaddr" ]; then
+			echo "Warning, \$macaddr is set. Using \$macaddr value $maccaddr"
+		else
+			macaddr=$mac_addr
+		fi
+	fi
+	if [ -n "$stp" ]; then
+		echo "$stp" > /sys/devices/virtual/net/${interface}/bridge/stp_state
+	else
+		echo "0" > /sys/devices/virtual/net/${interface}/bridge/stp_state
+	fi
 	if [ -n "$forwarding" ]; then
-                /sbin/sysctl net.ipv4.conf.${interface}.forwarding=${forwarding} >/dev/null 2>&1
-                /sbin/sysctl net.ipv6.conf.${interface}.forwarding=${forwarding} >/dev/null 2>&1
-        fi
+		/sbin/sysctl net.ipv4.conf.${interface}.forwarding=${forwarding} >/dev/null 2>&1
+		/sbin/sysctl net.ipv6.conf.${interface}.forwarding=${forwarding} >/dev/null 2>&1
+	fi
 }
 
 netif_destroy() {
-    local slave
-    local bcast
-    if [ -n "$slaves" ]; then
-        for slave in ${slaves//netif./}; do 
-            ip link set dev ${slave} no master
-        done
-    fi  
+	local slave
+	local bcast
+	if [ -n "$slaves" ]; then
+		for slave in ${slaves//netif./}; do 
+			ip link set dev ${slave} no master
+		done
+	fi
 
 	ip link delete dev  $interface
 }
@@ -51,7 +51,7 @@ netif_post_up() {
 		echo "There's a PID file for interface $interface. Aborting."
 		exit 2
 	fi
-	
+
 	$DHCPCD $interface
 }
 
@@ -60,7 +60,7 @@ netif_pre_up() {
 		echo "dhcpcd binary not found. Did you emerge net-misc/dhcpcd?"
 		exit 1
 	fi
-	
+
 	local slave
 	local bcast
 	if [ -n "$slaves" ]; then
@@ -82,14 +82,9 @@ netif_pre_up() {
 	done
 
 	for ipnm6 in $ipaddr6 $ipaddrs6; do
-	    ip -6 addr add $(get_ipnm_part "$ipnm6") $bcast dev $interface || die "Couldn't add $ipnm6 to $interface"
+		ip -6 addr add $(get_ipnm_part "$ipnm6") $bcast dev $interface || die "Couldn't add $ipnm6 to $interface"
 	done
-
-
-
 }
-
-
 
 netif_pre_down() {
 	if [ ! -f "${PIDFILE}" ]; then
diff --git a/netif.d/bridge-openvswitch b/netif.d/bridge-openvswitch
--- a/netif.d/bridge-openvswitch
+++ b/netif.d/bridge-openvswitch
@@ -1,75 +1,72 @@
 #!/bin/sh -x
 
 netif_depend() {
-        need ovsdb-server
-        need ovs-controller
-        need ovs-vswitchd
+	need ovsdb-server
+	need ovs-controller
+	need ovs-vswitchd
 }
 
 netif_create() {
-        ovs-vsctl --may-exist  add-br $interface
-        if [ -n "$mac_addr" ]; then
-             echo 'mac_addr is deprecated and will be removed. Please use "macaddr"'
-        if [ -n "$macaddr" ]; then
-        echo "Warning, \$macaddr is set. Using \$macaddr value $maccaddr"
-        else
-            macaddr=$mac_addr
-        fi
-    fi
+	ovs-vsctl --may-exist  add-br $interface
+	if [ -n "$mac_addr" ]; then
+		echo 'mac_addr is deprecated and will be removed. Please use "macaddr"'
+		if [ -n "$macaddr" ]; then
+			echo "Warning, \$macaddr is set. Using \$macaddr value $maccaddr"
+		else
+			macaddr=$mac_addr
+		fi
+	fi
 	:
 }
 
 netif_destroy() {
-        ovs-vsctl --if-exists del-br $interface
+	ovs-vsctl --if-exists del-br $interface
 }
 
 netif_pre_down() {
-        local slave
+	local slave
 
-        if [ -n "$slaves" ]; then
-                for slave in ${slaves//netif./}; do
-                        ovs-ofctl mod-port $interface ${slave} down
-                        ovs-vsctl --if-exists del-port $interface ${slave}
-                done
-        fi
+	if [ -n "$slaves" ]; then
+		for slave in ${slaves//netif./}; do
+			ovs-ofctl mod-port $interface ${slave} down
+			ovs-vsctl --if-exists del-port $interface ${slave}
+		done
+	fi
 
-        ovs-ofctl mod-port $interface $interface down
+	ovs-ofctl mod-port $interface $interface down
 }
 
 netif_pre_up() {
-        local slave
-        local bcast
-        if [ -n "$slaves" ]; then
-                for slave in ${slaves//netif./}; do
+	local slave
+	local bcast
+	if [ -n "$slaves" ]; then
+		for slave in ${slaves//netif./}; do
 			ip addr flush dev ${slave}
-                        ovs-vsctl --may-exist add-port $interface ${slave}
-                        ovs-ofctl mod-port $interface ${slave} up
-                done
-        fi
+			ovs-vsctl --may-exist add-port $interface ${slave}
+			ovs-ofctl mod-port $interface ${slave} up
+		done
+	fi
 
-        for ipnm in $ipaddr $ipaddrs; do
-            if [ -n "$(if_ipv4 $ipnm)" ]; then
-                bcast="broadcast $(get_option "$ipnm" broadcast +)"
-            else
-                bcast=""
-            fi
+	for ipnm in $ipaddr $ipaddrs; do
+		if [ -n "$(if_ipv4 $ipnm)" ]; then
+			bcast="broadcast $(get_option "$ipnm" broadcast +)"
+		else
+			bcast=""
+		fi
 
-            ip addr add $(get_ipnm_part "$ipnm") $bcast dev $interface || die "Couldn't add $ipnm to $interface"
-        done
-
-        for ipnm in $ipaddr $ipaddrs; do
-            ip -6 addr add $(get_ipnm_part "$ipnm") $bcast dev $interface || die "Couldn't add $ipnm to $interface"
+		ip addr add $(get_ipnm_part "$ipnm") $bcast dev $interface || die "Couldn't add $ipnm to $interface"
 	done
 
+	for ipnm in $ipaddr $ipaddrs; do
+		ip -6 addr add $(get_ipnm_part "$ipnm") $bcast dev $interface || die "Couldn't add $ipnm to $interface"
+	done
 
-        if [ -n "$stp" ]; then
-            ovs-vsctl --if-exists set bridge $interface stp_enable=true
-        fi
+	if [ -n "$stp" ]; then
+		ovs-vsctl --if-exists set bridge $interface stp_enable=true
+	fi
 
-        if [ -n "$forwarding" ]; then
-            /sbin/sysctl net.ipv4.conf.${interface}.forwarding=${forwarding} >/dev/null 2>&1
-            /sbin/sysctl net.ipv6.conf.${interface}.forwarding=${forwarding} >/dev/null 2>&1
-        fi
-
+	if [ -n "$forwarding" ]; then
+		/sbin/sysctl net.ipv4.conf.${interface}.forwarding=${forwarding} >/dev/null 2>&1
+		/sbin/sysctl net.ipv6.conf.${interface}.forwarding=${forwarding} >/dev/null 2>&1
+	fi
 }
-
diff --git a/netif.d/bridge-vde b/netif.d/bridge-vde
--- a/netif.d/bridge-vde
+++ b/netif.d/bridge-vde
@@ -5,7 +5,6 @@ if [ -z "$debug" ]; then
 fi
 
 netif_create() {
-
 	# Check to see if interface is already in use
 	if [ -z "${br_interace}" ]; then
 		iface_test="$(ip link | grep ${interface} | awk '{ print $2 }')"
@@ -26,7 +25,6 @@ netif_create() {
 		fi
 
 	fi
-
 
 	if [ -n "$vde_pidfile" ]; then
 		# Check if PID exists
@@ -85,7 +83,6 @@ netif_create() {
 		vde_sock_arg="--sock /var/tmp/vde.${br_interface}.ctl "
 	fi
 
-	
 	## Set up Phy Bridge to attach VDE too
 	ip link add name ${br_interface} type bridge
 
@@ -102,7 +99,6 @@ netif_create() {
 	if [ "$debug" -ge "2" ]; then
 		echo "Disabling STP, Use VDE's FSTP capability VIA RCFile instead"
 	fi
-
 
 	## Set up VDE_Switch
 
@@ -124,7 +120,6 @@ netif_create() {
 	if [ "$debug" -ge "2" ]; then
 		echo "vde group set to: ${vde_group_arg}"
 	fi
-
 
 	if [ -n "$vde_tap" ]; then
 		ip tuntap add dev ${vde_tap} mode tap group ${vde_group}
@@ -173,7 +168,6 @@ netif_create() {
 			echo "vde managment socket set to: ${vde_mgmt_arg}"
 		fi
 
-
 		if [ -n "$vde_hub" ]; then
 			vde_hub_arg="--hub " 
 			vde_hub="on"
@@ -190,80 +184,73 @@ netif_create() {
 			echo "vde args set to: $vde_args"
 		fi
 		vde_switch $vde_args
+}
 
+netif_destroy() {
+	if [ -n "$vde_mgmt" ]; then
+		vde_mgmt_arg="-s $vde_mgmt "
+	else
+		vde_mgmt_arg="-s /var/tmp/vde.${br_interface}.mgmt"
+	fi
+	if [ -n "$vde_pidfile" ]; then
+		vde_pid=`cat $vde_pidfile`
+	else
+		vde_pid=`cat /var/tmp/vde.${br_interface}.pid`
+	fi
+	if [ "$debug" -ge "2" ]; then
+		echo "attempt to stop the following VDE proccess:"
+		echo "vde_mgmt: $vde_mgmt_arg"
+		echo "vde_pid: $vde_pid"
+	fi
+	vdecmd_args="$vde_mgmt_arg shutdown"
+	vdecmd $vdecmd_args || kill -s TERM $vde_pid || echo "failed to kill vde_switch running on PID $vde_pid"
+}
 
-	}
-
-	netif_destroy() {
-
-		if [ -n "$vde_mgmt" ]; then
-			vde_mgmt_arg="-s $vde_mgmt "
+netif_pre_up() {
+	local slave
+	local bcast
+	if [ -n "$slaves" ]; then
+		for slave in ${slaves//netif./}; do
+			ip addr flush dev ${slave}
+			ip link set dev ${slave} master ${br_interface}
+			if [ "$debug" -ge "2" ]; then
+				echo "Setting dev ${slave} master to: ${br_interface}"
+			fi
+		done
+	fi	
+	for ipnm in $ipaddr $ipaddrs; do
+		if [ -n "$(if_ipv4 $ipnm)" ]; then
+			bcast="broadcast $(get_option "$ipnm" broadcast +)"
 		else
-			vde_mgmt_arg="-s /var/tmp/vde.${br_interface}.mgmt"
+			bcast=""
 		fi
-		if [ -n "$vde_pidfile" ]; then
-			vde_pid=`cat $vde_pidfile`
-		else
-			vde_pid=`cat /var/tmp/vde.${br_interface}.pid`
-		fi
+		ip addr add $(get_ipnm_part "$ipnm") $bcast dev $br_interface || die "Couldn't add $ipnm to $br_interface"
 		if [ "$debug" -ge "2" ]; then
-			echo "attempt to stop the following VDE proccess:"
-			echo "vde_mgmt: $vde_mgmt_arg"
-			echo "vde_pid: $vde_pid"
+			echo "Setting dev ${interface} IP to: ${ipm,}"
 		fi
-		vdecmd_args="$vde_mgmt_arg shutdown"
-		vdecmd $vdecmd_args || kill -s TERM $vde_pid || echo "failed to kill vde_switch running on PID $vde_pid"
+	done
 
-	}
+	for ipnm6 in $ipaddr6 $ipaddrs6; do
+		ip -6 addr add $(get_ipnm_part "$ipnm6") $bcast dev $br_interface || die "Couldn't add $ipnm6 to $br_interface"
+		if [ "$debug" -ge "2" ]; then
+			echo "Setting dev ${interface} IPv6 to: ${ipmn6}"
+		fi
+	done
+}
 
-	netif_pre_up() {
-		local slave
-		local bcast
-		if [ -n "$slaves" ]; then
-			for slave in ${slaves//netif./}; do
-				ip addr flush dev ${slave}
-				ip link set dev ${slave} master ${br_interface}
-				if [ "$debug" -ge "2" ]; then
-					echo "Setting dev ${slave} master to: ${br_interface}"
-				fi
-			done
-		fi	
-		for ipnm in $ipaddr $ipaddrs; do
-			if [ -n "$(if_ipv4 $ipnm)" ]; then
-				bcast="broadcast $(get_option "$ipnm" broadcast +)"
-			else
-				bcast=""
-			fi
-			ip addr add $(get_ipnm_part "$ipnm") $bcast dev $br_interface || die "Couldn't add $ipnm to $br_interface"
+netif_pre_down() {
+	ip link set dev ${vde_tap} nomaster
+	ip link delete dev ${vde_tap}
+
+	local slave
+	local bcast
+	if [ -n "$slaves" ]; then
+		for slave in ${slaves//netif./}; do
+			ip link set dev ${slave} nomaster
 			if [ "$debug" -ge "2" ]; then
-				echo "Setting dev ${interface} IP to: ${ipm,}"
+				echo "Setting dev ${slave} master to none"
 			fi
 		done
-
-		for ipnm6 in $ipaddr6 $ipaddrs6; do
-			ip -6 addr add $(get_ipnm_part "$ipnm6") $bcast dev $br_interface || die "Couldn't add $ipnm6 to $br_interface"
-			if [ "$debug" -ge "2" ]; then
-				echo "Setting dev ${interface} IPv6 to: ${ipmn6}"
-			fi
-		done
-
-	}
-
-	netif_pre_down() {
-
-
-		ip link set dev ${vde_tap} nomaster
-		ip link delete dev ${vde_tap}
-
-		local slave
-		local bcast
-		if [ -n "$slaves" ]; then
-			for slave in ${slaves//netif./}; do
-				ip link set dev ${slave} nomaster
-				if [ "$debug" -ge "2" ]; then
-					echo "Setting dev ${slave} master to none"
-				fi
-			done
-		fi	
-		ip link delete dev ${br_interface}
-	}
+	fi	
+	ip link delete dev ${br_interface}
+}
diff --git a/netif.d/vde-slirp b/netif.d/vde-slirp
--- a/netif.d/vde-slirp
+++ b/netif.d/vde-slirp
@@ -1,309 +1,297 @@
 #!/bin/sh
 
 netif_create() {
+	## Set up VDE_Switch
 
+	if [ -n "$vde_mode" ]; then
+		vde_mod_arg="--mode $vde_mode "
+		slirp_mod_arg="-m $vde_mode "
+	else
+		vde_mod_arg="--mode 660 "
+		slirp_mod_arg="-m 660"
+	fi
+	if [ "debug" -ge "2" ]; then
+		echo "Setting Slirp,VDE mode to: ${slirp_mod_arg//-m /}"
+	fi
 
-    ## Set up VDE_Switch
+	if [ -n "$vde_group" ]; then
+		vde_group_arg="--group $vde_group "
+	else
+		vde_group_arg="--group kvm "
+		vde_group="kvm"
+	fi
+	if [ "debug" -ge "2" ]; then
+		echo "vde group set to: ${vde_group}"
+	fi
 
-    if [ -n "$vde_mode" ]; then
-        vde_mod_arg="--mode $vde_mode "
-        slirp_mod_arg="-m $vde_mode "
-    else
-        vde_mod_arg="--mode 660 "
-        slirp_mod_arg="-m 660"
-    fi
-    if [ "debug" -ge "2" ]; then
-        echo "Setting Slirp,VDE mode to: ${slirp_mod_arg//-m /}"
-    fi
+	if [ -n "$vde_tap" ]; then
+		ip tuntap add dev ${vde_tap} mode tap group ${vde_group}
+		ip link set ${vde_tap} promisc on
+		ip link set ${vde_tap} up
+		vde_tap_arg="--tap $vde_tap "
+		if [ "debug" -ge "2" ]; then
+			echo "Using supplied vde_tap: ${vde_tap} for tap interface"
+		fi
+	else
+		if [ "debug" -ge "2" ]; then
+			echo "using service name ${interface} for vde_tap"
+		fi
+		vde_tap="${interface}"
+		ip tuntap add dev ${vde_tap} mode tap group ${vde_group}
+		ip link set ${vde_tap} promisc on
+		ip link set ${vde_tap} up
+		vde_tap_arg="--tap $vde_tap "
+	fi
 
-    if [ -n "$vde_group" ]; then
-        vde_group_arg="--group $vde_group "
-    else
-        vde_group_arg="--group kvm "
-        vde_group="kvm"
-    fi
-    if [ "debug" -ge "2" ]; then
-        echo "vde group set to: ${vde_group}"
-    fi
+	if [ -n "$vde_sock" ]; then
+		vde_sock_arg="--sock $vde_sock "
+	else
+		vde_sock_arg="--sock /var/tmp/vde.${interface}.ctl "
+		vde_sock="/var/tmp/vde.${interface}.ctl"
+	fi
+	if [ "debug" -ge "2" ]; then
+		echo "Setting vde socket to: $vde_socket"
+	fi
 
+	if [ -n "$vde_pidfile" ]; then
+		vde_pidfile_arg="--pidfile $vde_pid "
+	else
+		vde_pidfile_arg="--pidfile /var/tmp/vde.${interface}.pid "
+	fi
+	if [ "debug" -ge "2" ]; then
+		echo "Setting vde pid file to: ${vde_pidfile}"
+	fi
 
+	if [ -n "$slirp_pidfile" ]; then
+		slirp_pidfile_arg="--pidfile $slirp_pidfile "
+	else
+		slirp_pidfile_arg="--pidfile /var/tmp/slirp.${interface}.pid "
+	fi
+	if [ "debug" -ge "2" ]; then
+		echo "Setting slirp pid file to: ${slirp_pidfile}"
+	fi
 
-    if [ -n "$vde_tap" ]; then
-        ip tuntap add dev ${vde_tap} mode tap group ${vde_group}
-        ip link set ${vde_tap} promisc on
-        ip link set ${vde_tap} up
-        vde_tap_arg="--tap $vde_tap "
-        if [ "debug" -ge "2" ]; then
-            echo "Using supplied vde_tap: ${vde_tap} for tap interface"
-        fi
-    else
-        if [ "debug" -ge "2" ]; then
-            echo "using service name ${interface} for vde_tap"
-        fi
-        vde_tap="${interface}"
-        ip tuntap add dev ${vde_tap} mode tap group ${vde_group}
-        ip link set ${vde_tap} promisc on
-        ip link set ${vde_tap} up
-        vde_tap_arg="--tap $vde_tap "
-    fi
+	if [ -n "$vde_rcfile" ]; then
+		vde_rcfile_arg="--rcfile $vde_rcfile "
+	else
+		vde_rcfile_arg=""
+	fi
+	if [ "debug" -ge "2" ]; then
+		echo "Setting vde rcfile to: ${vde_rcfile}"
+	fi
 
-    if [ -n "$vde_sock" ]; then
-        vde_sock_arg="--sock $vde_sock "
-    else
-        vde_sock_arg="--sock /var/tmp/vde.${interface}.ctl "
-        vde_sock="/var/tmp/vde.${interface}.ctl"
-    fi
-    if [ "debug" -ge "2" ]; then
-        echo "Setting vde socket to: $vde_socket"
-    fi
+	if [ -n "$vde_mgmt" ]; then
+		vde_mgmt_arg="--mgmt $vde_mgmt "
+	else
+		vde_mgmt_arg="--mgmt /var/tmp/vde.${interface}.mgmt"
+		vde_mgmt="${vde_mgmt_arg//--mgmt/}"
+	fi
+	if [ "debug" -ge "2" ]; then
+		echo "Setting vde managment socket to: ${vde_mgmt}"
+	fi
 
-    if [ -n "$vde_pidfile" ]; then
-        vde_pidfile_arg="--pidfile $vde_pid "
-    else
-        vde_pidfile_arg="--pidfile /var/tmp/vde.${interface}.pid "
-    fi
-    if [ "debug" -ge "2" ]; then
-        echo "Setting vde pid file to: ${vde_pidfile}"
-    fi
+	if [  "$vde_hub" -eq "1" ]; then
+		vde_hub_arg="--hub " 
+		vde_hob="on"
+	else
+		vde_hub_arg=""
+		vde_hub="off"
+	fi
+	if [ "debug" -ge "2" ]; then
+		echo "VDE hub is: ${vde_hub}"
+	fi
 
-    if [ -n "$slirp_pidfile" ]; then
-        slirp_pidfile_arg="--pidfile $slirp_pidfile "
-    else
-        slirp_pidfile_arg="--pidfile /var/tmp/slirp.${interface}.pid "
-    fi
-    if [ "debug" -ge "2" ]; then
-        echo "Setting slirp pid file to: ${slirp_pidfile}"
-    fi
+	if [ -n "slirp_redir_tcp" ]; then
+		local redir_tcp
+		local redir_debug="Redirecting TCP ports:\n"
+		for redir_tcp in $slirp_redir_tcp; do
+			slirp_tcp_arg="-L ${redir_tcp} "
+			redir_debug="${redir_debug}${redir_tcp}\n"
+		done
+		if [ "debug" -ge "2" ]; then
+			echo "${redir_debug}"
+		fi
+	else
+		slirp_tcp_arg=""
+	fi
 
-    if [ -n "$vde_rcfile" ]; then
-        vde_rcfile_arg="--rcfile $vde_rcfile "
-    else
-        vde_rcfile_arg=""
-    fi
-    if [ "debug" -ge "2" ]; then
-        echo "Setting vde rcfile to: ${vde_rcfile}"
-    fi
+	if [ -n "slirp_redir_udp" ]; then
+		local redir_udp
+		local redir_debug="Redirecting UDP ports:\n"
+		for redir_udp in $slirp_redir_udp; do
+			slirp_udp_arg="-U ${redir_udp} "
+			redir_debug="${redir_debug}${redir_tcp}\n"
+		done
+		if [ "debug" -ge "2" ]; then
+			echo "${redir_debug}"
+		fi
+	else
+		slirp_udp_arg=""
+	fi
 
-    if [ -n "$vde_mgmt" ]; then
-        vde_mgmt_arg="--mgmt $vde_mgmt "
-    else
-        vde_mgmt_arg="--mgmt /var/tmp/vde.${interface}.mgmt"
-        vde_mgmt="${vde_mgmt_arg//--mgmt/}"
-    fi
-    if [ "debug" -ge "2" ]; then
-        echo "Setting vde managment socket to: ${vde_mgmt}"
-    fi
+	if [ -n "slirp_redir_x" ]; then
+		local redir_x
+		local redir_debug="Redirecting X displays:\n"
+		for redir_x in $slirp_redir_x; do
+			slirp_x_arg="-X ${redir_local} "
+			redir_debug="${redir_debug}${redir_tcp}\n"
+		done
+		if [ "debug" -ge "2" ]; then
+			echo "${redir_debug}"
+		fi
+	else
+		slirp_x_arg=""
+	fi
 
-    if [  "$vde_hub" -eq "1" ]; then
-        vde_hub_arg="--hub " 
-        vde_hob="on"
-    else
-        vde_hub_arg=""
-        vde_hub="off"
-    fi
-    if [ "debug" -ge "2" ]; then
-        echo "VDE hub is: ${vde_hub}"
-    fi
+	if [ -n "slirp_redir_socket" ]; then
+		local redir_socket
+		local redir_debug="Redirecting Unix Sockets:\n"
+		for redir_socket in $slirp_redir_socket; do
+			slirp_socket_arg="-x ${redir_socket} "
+			redir_debug="${redir_debug}${redir_tcp}\n"
+		done
+		if [ "debug" -ge "2" ]; then
+			echo "${redir_debug}"
+		fi
+	else
+		slirp_socket_arg=""
+	fi
 
-    if [ -n "slirp_redir_tcp" ]; then
-        local redir_tcp
-        local redir_debug="Redirecting TCP ports:\n"
-        for redir_tcp in $slirp_redir_tcp; do
-            slirp_tcp_arg="-L ${redir_tcp} "
-            redir_debug="${redir_debug}${redir_tcp}\n"
-        done
-        if [ "debug" -ge "2" ]; then
-            echo "${redir_debug}"
-        fi
-    else
-        slirp_tcp_arg=""
-    fi
+	if [ "$slirp_dhcp" -eq "1" ]; then
+		if [ -n "slirp_dhcp_start" ]; then
+			slirp_dhcp_arg="--dhcp=${slirp_dhcp_start} "
+			if [ "debug" -ge "2" ]; then
+				echo "Setting DHCP starting range to: ${slirp_dhcp_start}"
+			fi
+		else
+			slirp_dhcp_arg="--dhcp  "
+			if [ "debug" -ge "2" ]; then
+				echo "Setting DHCP starting range to: Default"
+			fi
+		fi
+	else
+		slirp_dhcp_arg=""
+		if [ "debug" -ge "2" ]; then
+			echo "Slirp DHCP not enabled"
+		fi
+	fi
 
-    if [ -n "slirp_redir_udp" ]; then
-        local redir_udp
-        local redir_debug="Redirecting UDP ports:\n"
-        for redir_udp in $slirp_redir_udp; do
-            slirp_udp_arg="-U ${redir_udp} "
-            redir_debug="${redir_debug}${redir_tcp}\n"
-        done
-        if [ "debug" -ge "2" ]; then
-            echo "${redir_debug}"
-        fi
-    else
-        slirp_udp_arg=""
-    fi
+	if [ -n "$slirp_tftp" ]; then
+		slirp_tftp="--tftp ${slirp_tftp} "
+		if [ "debug" -ge "2" ]; then
+			echo "Slirp tftp server enabled for directory: ${slirp_tftp}"
+		fi
+	else
+		slirp_tftp=""
+		if [ "debug" -ge "2" ]; then
+			echo "Slirp tftp server not enabled"
+		fi
+	fi
 
-    if [ -n "slirp_redir_x" ]; then
-        local redir_x
-        local redir_debug="Redirecting X displays:\n"
-        for redir_x in $slirp_redir_x; do
-            slirp_x_arg="-X ${redir_local} "
-            redir_debug="${redir_debug}${redir_tcp}\n"
-        done
-        if [ "debug" -ge "2" ]; then
-            echo "${redir_debug}"
-        fi
-    else
-        slirp_x_arg=""
-    fi
+	if [ -n "$slirp_host" ]; then
+		slirp_host_arg="--host ${slirp_host} "
+		if [ "debug" -ge "2" ]; then
+			echo "Slirp host address set to: ${slirp_host}"
+		fi
+	else
+		slirp_host_arg=""
+		if [ "debug" -ge "2" ]; then
+			echo "Slirp host address set to: Default"
+		fi
+	fi
 
-    if [ -n "slirp_redir_socket" ]; then
-        local redir_socket
-        local redir_debug="Redirecting Unix Sockets:\n"
-        for redir_socket in $slirp_redir_socket; do
-            slirp_socket_arg="-x ${redir_socket} "
-            redir_debug="${redir_debug}${redir_tcp}\n"
-        done
-        if [ "debug" -ge "2" ]; then
-            echo "${redir_debug}"
-        fi
-    else
-        slirp_socket_arg=""
-    fi
+	if [ -n "$slirp_dns" ]; then
+		slirp_dns_arg="--dns $slirp_dns "
+		if [ "debug" -ge "2" ]; then
+			echo "Slirp DNS server/proxy set to: ${slirp_dns}"
+		fi
+	else
+		slirp_dns_arg=""
+		if [ "debug" -ge "2" ]; then
+			echo "Slirp DNS Server set to: Default"
+		fi
+	fi
 
-    if [ "$slirp_dhcp" -eq "1" ]; then
-        if [ -n "slirp_dhcp_start" ]; then
-            slirp_dhcp_arg="--dhcp=${slirp_dhcp_start} "
-            if [ "debug" -ge "2" ]; then
-                echo "Setting DHCP starting range to: ${slirp_dhcp_start}"
-            fi
-        else
-            slirp_dhcp_arg="--dhcp  "
-            if [ "debug" -ge "2" ]; then
-                echo "Setting DHCP starting range to: Default"
-            fi
-        fi
-    else
-        slirp_dhcp_arg=""
-        if [ "debug" -ge "2" ]; then
-            echo "Slirp DHCP not enabled"
-        fi
-    fi
+	if [ -n "$slirp_net" ]; then
+		slirp_net=_arg"--network ${slirp_net} "
+		if [ "debug" -ge "2" ]; then
+			echo "Slirp network set to: ${slirp_net}"
+		fi
+	else
+		slirp_net_arg=""
+		if [ "debug" -ge "2" ]; then
+			echo "Slirp network address set to: Default"
+		fi
+	fi
 
-    if [ -n "$slirp_tftp" ]; then
-        slirp_tftp="--tftp ${slirp_tftp} "
-        if [ "debug" -ge "2" ]; then
-            echo "Slirp tftp server enabled for directory: ${slirp_tftp}"
-        fi
-    else
-        slirp_tftp=""
-        if [ "debug" -ge "2" ]; then
-            echo "Slirp tftp server not enabled"
-        fi
-    fi
+	vde_args=" $vde_pidfile_arg $vde_hub_arg $vde_rcfile_arg $vde_mgmt_arg $vde_mod_arg $vde_group_arg "
+	vde_args="${vde_args} $vde_tap_arg $vde_sock_arg -daemon"
 
-    if [ -n "$slirp_host" ]; then
-        slirp_host_arg="--host ${slirp_host} "
-        if [ "debug" -ge "2" ]; then
-            echo "Slirp host address set to: ${slirp_host}"
-        fi
-    else
-        slirp_host_arg=""
-        if [ "debug" -ge "2" ]; then
-            echo "Slirp host address set to: Default"
-        fi
-    fi
+	slirp_args=" $vde_group_arg $vde_sock_arg $slirp_mod_arg $slirp_pidfile_arg $slirp_host_arg $slirp_dns_arg $slip_net_arg "
+	slirp_args="$slirp_args $slirp_tftp_arg $slirp_socket_arg $slirp_x_arg $slirp_udp_arg $slirp_tcp_arg -daemon"
 
-    if [ -n "$slirp_dns" ]; then
-        slirp_dns_arg="--dns $slirp_dns "
-        if [ "debug" -ge "2" ]; then
-            echo "Slirp DNS server/proxy set to: ${slirp_dns}"
-        fi
-    else
-        slirp_dns_arg=""
-        if [ "debug" -ge "2" ]; then
-            echo "Slirp DNS Server set to: Default"
-        fi
-    fi
-
-    if [ -n "$slirp_net" ]; then
-        slirp_net=_arg"--network ${slirp_net} "
-        if [ "debug" -ge "2" ]; then
-            echo "Slirp network set to: ${slirp_net}"
-        fi
-    else
-        slirp_net_arg=""
-        if [ "debug" -ge "2" ]; then
-            echo "Slirp network address set to: Default"
-        fi
-    fi
-
-
-    vde_args=" $vde_pidfile_arg $vde_hub_arg $vde_rcfile_arg $vde_mgmt_arg $vde_mod_arg $vde_group_arg "
-    vde_args="${vde_args} $vde_tap_arg $vde_sock_arg -daemon"
-
-    slirp_args=" $vde_group_arg $vde_sock_arg $slirp_mod_arg $slirp_pidfile_arg $slirp_host_arg $slirp_dns_arg $slip_net_arg "
-    slirp_args="$slirp_args $slirp_tftp_arg $slirp_socket_arg $slirp_x_arg $slirp_udp_arg $slirp_tcp_arg -daemon"
-
-    if [ "debug" -ge "2" ]; then
-        echo "slirp_args: $slirp_args"
-        echo "vde_args: $vde_args"
-    fi
-    vde_switch $vde_args
-    slirpvde $slirp_args
-
-
+	if [ "debug" -ge "2" ]; then
+		echo "slirp_args: $slirp_args"
+		echo "vde_args: $vde_args"
+	fi
+	vde_switch $vde_args
+	slirpvde $slirp_args
 }
 
 netif_destroy() {
+	if [ -n "${vde_mgmt}" ]; then
+		vde_mgmt_arg="-s ${vde_mgmt} "
+	else
+		vde_mgmt_arg="-s /var/tmp/vde.${vde_tap}.mgmt"
+	fi
+	if [ -n "${vde_pidfile}" ]; then
+		vde_pid=`cat ${vde_pidfile}`
+	else
+		vde_pid=`cat /var/tmp/vde.${interface}.pid`
+	fi
+	if [ -n "${slirp_pidfile}" ]; then
+		slirp_pid=`cat ${slirp_pidfile}`
+	else
+		slirp_pid=`cat /var/tmp/slirp.${interface}.pid`
+	fi
+	if [ "debug" -ge "1" ]; then
+		echo "Terminating the following VDE and SLIRP processes:"
+		echo "vde_mgmt: ${vde_mgmt_arg}"
+		echo "vde_pid: ${vde_pid}"
+		echo "slirp_pid: ${slirp_pid}"
+	fi
 
-    if [ -n "${vde_mgmt}" ]; then
-        vde_mgmt_arg="-s ${vde_mgmt} "
-    else
-        vde_mgmt_arg="-s /var/tmp/vde.${vde_tap}.mgmt"
-    fi
-    if [ -n "${vde_pidfile}" ]; then
-        vde_pid=`cat ${vde_pidfile}`
-    else
-        vde_pid=`cat /var/tmp/vde.${interface}.pid`
-    fi
-    if [ -n "${slirp_pidfile}" ]; then
-        slirp_pid=`cat ${slirp_pidfile}`
-    else
-        slirp_pid=`cat /var/tmp/slirp.${interface}.pid`
-    fi
-    if [ "debug" -ge "1" ]; then
-        echo "Terminating the following VDE and SLIRP processes:"
-        echo "vde_mgmt: ${vde_mgmt_arg}"
-        echo "vde_pid: ${vde_pid}"
-        echo "slirp_pid: ${slirp_pid}"
-    fi
+	vdecmd_args="${vde_mgmt_arg} shutdown"
+	kill -s TERM ${slirp_pid} && if [ -n "`ps -p ${slirp_pid} | grep -v "PID"`" ]; then
+		die "failed to kill slirpvde running on ${slirp_pid}"
+	else
+		echo "killed slirpvde proccess running on ${slirp_pid}"
+	fi
+	vdecmd ${vdecmd_args} || kill -s TERM ${vde_pid} || die "failed to kill vde_switch running on PID ${vde_pid}"
+}
 
-    vdecmd_args="${vde_mgmt_arg} shutdown"
-    kill -s TERM ${slirp_pid} && if [ -n "`ps -p ${slirp_pid} | grep -v "PID"`" ]; then
-    die "failed to kill slirpvde running on ${slirp_pid}"
-else
-    echo "killed slirpvde proccess running on ${slirp_pid}"
-fi
-vdecmd ${vdecmd_args} || kill -s TERM ${vde_pid} || die "failed to kill vde_switch running on PID ${vde_pid}"
+netif_pre_up() {
+	for ipnm in ${ipaddr} ${ipaddrs}; do
+		if [ -n "$(if_ipv4 $ipnm)" ]; then
+			bcast="broadcast $(get_option "${ipnm}" broadcast +)"
+		else
+			bcast=""
+		fi
+		ip addr add $(get_ipnm_part "${ipnm}") ${bcast} dev ${vde_tap} || die "Couldn't add ${ipnm} to ${vde_tap}"
+		if [ "debug" -ge "2" ]; then
+			echo "Setting Dev ${vde_tap} ipv4 to: ${ipnm}"
+		fi
+	done
 
-        }
+	for ipnm6 in ${ipaddr6} ${ipaddrs6}; do
+		ip -6 addr add $(get_ipnm_part "${ipnm6}") ${bcast} dev ${vde_tap} || die "Couldn't add ${ipnm6} to ${vde_tap}"
+		if [ "debug" -ge "2" ]; then
+			echo "Setting Dev ${vde_tap} ipv6 to: ${ipnm6}"
+		fi
+	done
+}
 
-        netif_pre_up() {
-            for ipnm in ${ipaddr} ${ipaddrs}; do
-                if [ -n "$(if_ipv4 $ipnm)" ]; then
-                    bcast="broadcast $(get_option "${ipnm}" broadcast +)"
-                else
-                    bcast=""
-                fi
-                ip addr add $(get_ipnm_part "${ipnm}") ${bcast} dev ${vde_tap} || die "Couldn't add ${ipnm} to ${vde_tap}"
-                if [ "debug" -ge "2" ]; then
-                    echo "Setting Dev ${vde_tap} ipv4 to: ${ipnm}"
-                fi
-            done
-
-            for ipnm6 in ${ipaddr6} ${ipaddrs6}; do
-                ip -6 addr add $(get_ipnm_part "${ipnm6}") ${bcast} dev ${vde_tap} || die "Couldn't add ${ipnm6} to ${vde_tap}"
-                if [ "debug" -ge "2" ]; then
-                    echo "Setting Dev ${vde_tap} ipv6 to: ${ipnm6}"
-                fi
-            done
-
-        }
-
-        netif_pre_down() {
-
-            ip link set dev ${vde_tap} nomaster
-            ip link delete dev ${vde_tap}
-
-        }
+netif_pre_down() {
+	ip link set dev ${vde_tap} nomaster
+	ip link delete dev ${vde_tap}
+}
