first attempt at setting default broadcast - also includes modular system for setting ipnm params

diff --git a/netif.d/bridge b/netif.d/bridge
--- a/netif.d/bridge
+++ b/netif.d/bridge
@@ -17,6 +17,8 @@ netif_pre_up() {
 	fi	
 	brctl setfd $interface 0 
 	for ipnm in $ipaddr $ipaddrs; do
-		ip addr add $ipnm dev $interface || die "Couldn't add $ipnm to $interface"
+		ip addr add $(get_ipnm_part "$ipnm") \
+		broadcast $(get_option "$ipnm" broadcast +) \
+		dev $interface || die "Couldn't add $ipnm to $interface"
 	done
 }
diff --git a/netif.d/interface b/netif.d/interface
--- a/netif.d/interface
+++ b/netif.d/interface
@@ -10,9 +10,13 @@ netif_pre_up() {
 		fi
 		if [ -z "$label" ]
 		then
-			ip addr add $ipnm dev $interface || die "Couldn't add $ipnm to $interface"
+			ip addr add $(get_ipnm_part "$ipnm") \
+				broadcast $(get_option "$ipnm" broadcast +)  \
+				dev $interface || die "Couldn't add $ipnm to $interface"
 		else
-			ip addr add $ipnm label $label dev $interface || die "Couldn't add $ipnm to $interface"
+			ip addr add $(get_ipnm_part "$ipnm") \
+				broadcast $(get_option "$ipnm" broadcast +) \
+				label $label dev $interface || die "Couldn't add $ipnm to $interface"
 		fi
 		count=$(( $count + 1 ))	
 	done
