preliminary netif VLAN support - needs testing

diff --git a/netif.d/interface b/netif.d/interface
--- a/netif.d/interface
+++ b/netif.d/interface
@@ -1,7 +1,17 @@
 #!/bin/bash
 
+netif_depend() {
+	[ -n "${trunk}" ] && need "netif.${trunk}"
+}
+
 start() {
 	ebegin "$STARTD"
+	
+	# VLANS:
+	if [ -n "${trunk}" ]; then
+		ip link add dev ${interface} link ${trunk} type vlan id ${interface##*.} || die "Couldn't configure VLAN ${vlan} on ${trunk}"
+	fi
+
 	ip addr flush dev $interface
 	for ipnm in $ipaddr $ipaddrs
 	do
@@ -17,5 +27,9 @@ stop() {
 	ezresolv del; ezroute del
 	ip link set $interface down 
 	ip addr flush dev $interface
+
+	# VLANS:
+	[ -n "${interface##*.}" ] && ip link delete ${interface}
+
 	eend 0
 }
