Initial support for configuring SR-IOV virtual network interface functions as regular Funtoo interfaces.

diff --git a/init.d/netif.tmpl b/init.d/netif.tmpl
--- a/init.d/netif.tmpl
+++ b/init.d/netif.tmpl
@@ -99,14 +99,14 @@ depend() {
 start() {
 	ebegin "$STARTD"
 	netif_create
-	if [ "$macaddr" != "" ]; then
+	if [ "$macaddr" != "" -a "$vlanmode" != "sriov" ]; then
 		/sbin/nameif ${interface} ${macaddr} || die "Couldn't rename interface"
 	fi
 	if [ ! -d /proc/sys/net/ipv6 ]; then
 		# attempt to silently load ipv6 module
 		modprobe -q ipv6
 	fi
-	if [ "$vlanmode" != "off" -a "$vlanmode" != "script" ]; then #configure vlan only if not managed by netif_* script
+	if [ "$vlanmode" != "off" -a "$vlanmode" != "script" -a "$vlanmode" != "sriov" ]; then #configure vlan only if not managed by netif_* script or sriov
 		if [ ! -d /proc/net/vlan ]; then
 			modprobe -q 8021q
 			if [ ! -d /proc/net/vlan ]; then
@@ -117,10 +117,32 @@ start() {
 		require trunk vlan
 		trunk_int="$(get_trunk_int ${trunk})"
 		ip link add name ${interface} link ${trunk_int} type vlan id ${vlan} || die "Couldn't configure VLAN ${vlan} on ${trunk}"
+	elif [ "$vlanmode" = "sriov" ]; then
+		trunk_int="$(get_trunk_int ${trunk})"
+		if [ -n "$vlan" ]; then
+			ip link set ${trunk_int} vf ${virtfn} vlan ${vlan} qos ${priority-0}
+		fi
+		if [ -z "$mac_replace" ]; then
+			mac_replace="$macaddr"
+		fi
+		if [ -z "$mac_replace" ]; then
+			trunk_mac="$(ip link show dev ${trunk_int} | awk '/link\/ether/{print $2}' || echo '00:00:00:00:00:00' )"
+			mac_replace="$(get_virtfn_mac ${virtfn} ${trunk_mac})"
+		fi
+		ip link set ${trunk_int} vf ${virtfn} mac ${mac_replace}
+		ip link set ${trunk_int} vf ${virtfn} spoofchk ${spoofchk-on}
+		virtfn_dev="$(get_virtfn_dev ${trunk_int} ${virtfn})"
+		if [ -z "$virtfn_dev" ]; then
+			eend 0; return
+		fi
+		if [ "$virtfn_dev" != "$interface" ]; then
+			/sbin/nameif ${interface} ${mac_replace}
+		fi
 	fi
 	ip addr flush dev $interface scope global > /dev/null 2>&1
+	set_sriov_numvfs "$numvfs"
 	netif_pre_up
-	if [ -n "$mac_replace" ]; then
+	if [ -n "$mac_replace" -a "$vlanmode" != "sriov" ]; then
 		ip link set dev $interface address $mac_replace || die "Couldn't set MAC to $mac_replace."
 	fi
 	debug ip link set $interface up
@@ -146,11 +168,20 @@ start() {
 		eend $?
 	fi
 	netif_post_up
+	if [ -n "$virtfn" ]; then
+		trunk_int="$(get_trunk_int ${trunk})"
+		if ! get_virtfn_dev >/dev/null ; then
+			ip link set ${trunk_int} vf ${virtfn} vlan 0
+			ip link set ${trunk_int} vf ${virtfn} spoofchk on
+			eend 0; return
+		fi
+	fi
 	eend $?
 }
 
 stop() {
 	ebegin "$STOPD"
+	set_sriov_numvfs 0
 	netif_pre_down
 	ezrule 6 del; ezrule 4 del
 	ezresolv del; ezroute 6 del; ezroute 4 del
@@ -159,7 +190,12 @@ stop() {
 	ip addr flush dev $interface scope global
 	netif_post_down
 	# VLANS:
-	[ "${vlanmode}" != "off" -a "$vlanmode" != "script" ] && ip link delete ${interface}
+	[ "${vlanmode}" != "off" -a "$vlanmode" != "script" -a "$vlanmode" != "sriov" ] && ip link delete ${interface}
+	if [ "$vlanmode" == "sriov" ]; then
+		ip link set ${trunk_int} vf ${virtfn} vlan 0
+		ip link set ${trunk_int} vf ${virtfn} spoofchk on
+		ip link set ${trunk_int} vf ${virtfn} mac "00:00:00:00:00:00"
+	fi
 	netif_destroy
 	eend 0
 }
@@ -240,6 +276,56 @@ get_trunk_int() {
 	else
 		echo $1
 	fi
+}
+
+# derive a default fixed mac address for sr-iov virtual functions by setting the
+# first octet to indicate a locally administered mac, the second two octets to encode
+# the virtual function number in hex (allowing up to 16K VF's) and repeating the 
+# physical function's last three octets so that the physical device is recognizable
+
+# arg1: virtfn number
+# arg2: physfn mac address
+get_virtfn_mac() {
+	local tmp2="$(( ( $1 & 0xFF00 ) >> 8 ))"
+	local tmp3="$(( $1 & 0xFF ))"
+	local oct1="02"
+	local oct2="$(printf "%02x" $tmp2)"
+	local oct3="$(printf "%02x" $tmp3)"
+	local oct4="$(echo $2 | cut -f4 -d:)"
+	local oct5="$(echo $2 | cut -f5 -d:)"
+	local oct6="$(echo $2 | cut -f6 -d:)"
+	echo "$oct1:$oct2:$oct3:$oct4:$oct5:$oct6"
+}
+
+# find out the logical device name of the given virtual function
+# arg1: trunk_int
+# arg2: virtfn number
+get_virtfn_dev() {
+	if [ -d "/sys/class/net" ]; then
+		local virtnetpath="/sys/class/net/$1/device/virtfn$2/net"
+		if [ ! -d "$virtnetpath" ]; then
+			return 1
+		fi
+		ls /sys/class/net/$1/device/virtfn$2/net | head -n 1
+	else
+		echo "Funtoo cannot handle SR-IOV networking on non-Linux kernels." >&2
+		echo "If this message surprises you, check that /sys/ is mounted." >&2
+		exit 1
+	fi
+}
+
+# set the number of active virtual functions
+# arg1: integer
+set_sriov_numvfs() {
+	local wanted="$1"
+	[ -z "$wanted" -o -z "$maxvfs" ] && return 0
+	local target="/sys/class/net/${interface}/device/sriov_numvfs"
+	local current="$(cat "$target" 2>/dev/null)"
+	[ -z "$current" -o "$wanted" == "$current" ] && return 0
+	echo 0 > "$target"
+	[ "$wanted" -eq 0 ] && return 0
+	echo "$wanted" > "$target"
+	return $?
 }
 
 start_pre() {
@@ -341,16 +427,36 @@ ezrule() {
 	fi
 }
 
-if [ -z "$trunk" -a -z "$vlanmode" ]; then
+if [ -z "$virtfn" -a -z "$trunk" -a -z "$vlanmode" ]; then
 	# auto-detect trunk/vlan ID from interface name
 	vlanmode="auto"
 	vlan="${interface##*.}"
 	trunk="${interface%.*}"
 	[ "$vlan" = "$interface" ] && vlanmode="off"
+elif [ -n "$virtfn" ]; then
+	# trunk/vlan ID configures sr-iov virtual function
+	vlanmode="sriov"
+	require trunk
 else
 	# trunk/vlan ID specified by user in config
 	: ${vlanmode:="custom"} #don't overwrite vlanmode if already specified
 	require vlan
+fi
+
+# skip this check when /sys isn't mounted yet
+if [ -n "$numvfs" -a -d "/sys/class/net" ]; then
+	if [ "$vlanmode" != "off" ]; then
+		echo "ERROR: cannot set up SR-IOV from a VLAN interface." >&2
+		exit 1
+	fi
+	maxvfs="$(cat /sys/class/net/${interface}/device/sriov_totalvfs 2>/dev/null)"
+	if [ -z "$maxvfs" -a -n "$numvfs" ]; then
+		echo "ERROR: ${interface} does not support virtual functions."
+		exit 1
+	fi
+	if [ "$numvfs" -lt 1 -o "$numvfs" -gt "$maxvfs" ]; then
+		numvfs="$maxvfs"
+	fi
 fi
 
 . /etc/netif.d/$template
