add dhcpc existence check
If dhcp is set to "yes", then check before any action
that $DHCPC exist.

diff --git a/init.d/netif.tmpl b/init.d/netif.tmpl
--- a/init.d/netif.tmpl
+++ b/init.d/netif.tmpl
@@ -29,6 +29,10 @@ STOPD="Network $DESC2 $CYAN$interface$OFF down"
 if [ "$dhcp" = "yes" ]; then
 	DHCPC=${DHCPC:-"/sbin/dhcpcd"}
 	DHCPC_PIDFILE="/var/run/dhcpcd-${interface}.pid"
+	if [ ! -f "${DHCPC}" ]; then
+		echo "dhcpcd binary not found. Did you emerge net-misc/dhcpcd?"
+		exit 1
+	fi
 fi
 
 require() {
