check for error condition on interface renaming, since this is a fatal error

diff --git a/init.d/netif.tmpl b/init.d/netif.tmpl
--- a/init.d/netif.tmpl
+++ b/init.d/netif.tmpl
@@ -64,7 +64,7 @@ start() {
 	ebegin "$STARTD"
 	netif_create
 	if [ "$macaddr" != "" ]; then
-		/sbin/nameif ${interface} ${macaddr}
+		/sbin/nameif ${interface} ${macaddr} || die "Couldn't rename interface"
 	fi
 	if [ "$vlanmode" != "off" ]; then
 	       	if [ ! -d /proc/net/vlan ]; then
