FL-1886: fix vlan interface creation

diff --git a/init.d/netif.tmpl b/init.d/netif.tmpl
--- a/init.d/netif.tmpl
+++ b/init.d/netif.tmpl
@@ -94,7 +94,7 @@ start() {
 			fi
 		fi
 		require trunk vlan
-		ip link add dev ${interface} link ${trunk} type vlan id ${vlan} || die "Couldn't configure VLAN ${vlan} on ${trunk}"
+		ip link add name ${interface} link ${trunk} type vlan id ${vlan} || die "Couldn't configure VLAN ${vlan} on ${trunk}"
 	fi
 	ip addr flush dev $interface scope global > /dev/null 2>&1
 	netif_pre_up
